title: City sysc-A Comprehensive approach to urban living. 
description: A comprehensive approach to urban living focuses on sustainability, smart infrastructure, and community well-being.
            It balances environmental, social, and economic factors for resilient and efficient cities.
theme: jekyll-theme-cayman
